POST http://localhost:3001/api/patients HTTP/1.1
Content-Type: application/json

{
  "name": "someone else",
  "dateOfBirth": "1980-12-23",
  "ssn": "34353535-F54",
  "gender": "male",
  "occupation": "new jober",
  "entries": []
}
