POST http://localhost:3003/api/users/
Content-Type: application/json

{
  "username": "root",
  "name": "Superuser",
  "password": "sekret"
}

###

POST http://localhost:3003/api/users/
Content-Type: application/json

{
  "username": "mluukkai",
  "name": "Matti Luukkainen",
  "password": "salainen"
}
