POST http://localhost:4000/
Content-Type: application/json

{
  "query": "query { bookCount, authorCount }"
}

#####

POST http://localhost:4000/
Content-Type: application/json

{
  "query": "query { allBooks { title, author, published, genres } }"
}

#####

POST http://localhost:4000/
Content-Type: application/json

{
  "query": "query { allAuthors { name, bookCount } }"
}

#####

POST http://localhost:4000/
Content-Type: application/json

{
  "query": "query { allBooks(author: \"Robert Martin\") { title } }"
}

